In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
# Viết chương trình sử dụng hàm zeros tạo Numpy array, Tensorflow tensor, Pytorch tensor chỉ chứa giá trị là số 0 với kích thước (3,4)
arr_zeros = np.zeros((3,4))
print(arr_zeros)
torch_tensor_zeros = torch.zeros((3,4))
print(torch_tensor_zeros)
tf_tensor_zeros = tf.zeros((3,4))
print(tf_tensor_zeros)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [4]:
# Viết chương trình sử dụng hàm zeros tạo Numpy array, Tensorflow tensor, Pytorch tensor chỉ chứa giá trị là số 1 với kích thước (3,4)
arr_ones = np.ones((3,4))
print(arr_ones)
torch_tensor_ones = torch.ones((3,4))
print(torch_tensor_ones)
tf_tensor_ones = tf.ones((3,4))
print(tf_tensor_ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [3]:
# # Viết chương trình sử dụng hàm zeros tạo Numpy array, Tensorflow tensor, Pytorch tensor chỉ chứa giá trị là số 5 với kích thước (3,4)
arr_full = np.full((3,4),5)
print(arr_full)
torch_tensor_full = torch.full((3,4),5)
print(torch_tensor_full)
tf_tensor_fill = tf.fill((3,4),5)
print(tf_tensor_fill)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
