In [1]:
import random
import numpy as np
import torch
import tensorflow as tf

In [14]:
random.seed(2024)
# Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10,10) với kích thức (3,4). Sau đó chuyển vị array, tensor thứ 2 và thực hiện pháp nhân matrix multiplication. Lưu ý: sử dụng seed = 2024
arr1, arr2 = [0] * 3, [0] * 3
for i in range(3):
    arr1[i], arr2[i] = [0] * 4, [0] * 4
for row in arr1:
    for idx in range(len(row)):
        row[idx] = random.randint(-10,9)
for row in arr2:
    for idx in range(len(row)):
        row[idx] = random.randint(-10,9)
print(arr1)
print(arr2)

[[5, -5, 8, -1], [-4, 3, -2, 7], [-3, 5, 1, 3]]
[[6, 9, -4, -1], [7, 0, 6, -8], [-4, 4, -6, 7]]


In [33]:
np_arr1 = np.array(arr1)
np_arr2 = np.array(arr2)
print('Numpy Array 1: \n', np_arr1)
print('Numpy Array 2: \n', np_arr2)
print(f'Nhân Numpy Array 1 với Chuyển vị của Numpy Array 2: \n{np.matmul(np_arr1,np_arr2.T)}')


Numpy Array 1: 
 [[ 5 -5  8 -1]
 [-4  3 -2  7]
 [-3  5  1  3]]
Numpy Array 2: 
 [[ 6  9 -4 -1]
 [ 7  0  6 -8]
 [-4  4 -6  7]]
Nhân Numpy Array 1 với Chuyển vị của Numpy Array 2: 
[[-46  91 -95]
 [  4 -96  89]
 [ 20 -39  47]]


In [28]:
tensor1 = torch.tensor(arr1)
tensor2 = torch.tensor(arr2)
print('Torch Tensor 1: \n', tensor1)
print('Torch Tensor 2: \n', tensor2)
print(f'Nhân Tensor 1 với Chuyển vị của Tensor 2: \n{torch.matmul(tensor1,tensor2.T)}')

Torch Tensor 1: 
 tensor([[ 5, -5,  8, -1],
        [-4,  3, -2,  7],
        [-3,  5,  1,  3]])
Torch Tensor 2: 
 tensor([[ 6,  9, -4, -1],
        [ 7,  0,  6, -8],
        [-4,  4, -6,  7]])
Nhân Tensor 1 với Chuyển vị của Tensor 2: 
tensor([[-46,  91, -95],
        [  4, -96,  89],
        [ 20, -39,  47]])


In [31]:
tf_tensor1 = tf.constant(arr1)
tf_tensor2 = tf.constant(arr2)
print('Torch Tensor 1: \n', tf_tensor1)
print('Torch Tensor 2: \n', tf_tensor2)
print(f'Nhân Tensor 1 với Chuyển vị của Tensor 2: \n{tf.matmul(tensor1,tf.transpose(tensor2))}')

Torch Tensor 1: 
 tf.Tensor(
[[ 5 -5  8 -1]
 [-4  3 -2  7]
 [-3  5  1  3]], shape=(3, 4), dtype=int32)
Torch Tensor 2: 
 tf.Tensor(
[[ 6  9 -4 -1]
 [ 7  0  6 -8]
 [-4  4 -6  7]], shape=(3, 4), dtype=int32)
Nhân Tensor 1 với Chuyển vị của Tensor 2: 
[[-46  91 -95]
 [  4 -96  89]
 [ 20 -39  47]]


In [35]:
# Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10,10) với kích thức (3,3). Sau đó hãy tính tổng của toàn bộ tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang. Lưu ý sử dụng seed = 2024
arr3 = [0] * 3
for i in range(3):
    arr3[i] = [0] * 3
for row in arr3:
    for idx in range(len(row)):
        row[idx] = random.randint(-10,9)
print(arr3)

[[-4, 3, -3], [-4, -9, -3], [-10, -2, 6]]


In [38]:
np_arr3 = np.array(arr3)
print('Numpy Array : \n', np_arr3)
print(f'Tổng của toàn bộ Numpy Array: \n{np.sum(np_arr3)}')
print(f'Tổng của Numpy Array theo cột: \n{np.sum(np_arr3, axis=0)}')
print(f'Tổng của Numpy Array theo hàng: \n{np.sum(np_arr3, axis=1)}')

Numpy Array : 
 [[ -4   3  -3]
 [ -4  -9  -3]
 [-10  -2   6]]
Tổng của toàn bộ Numpy Array: 
-26
Tổng của Numpy Array theo cột: 
[-18  -8   0]
Tổng của Numpy Array theo hàng: 
[ -4 -16  -6]


In [40]:
tensor3 = torch.Tensor(arr3)
print('Torch Tensor : \n', tensor3)
print(f'Tổng của toàn bộ Torch Tensor: \n{torch.sum(tensor3)}')
print(f'Tổng của Torch Tensor theo cột: \n{torch.sum(tensor3, axis=0)}')
print(f'Tổng của Torch Tensor theo hàng: \n{torch.sum(tensor3, axis=1)}')

Torch Tensor : 
 tensor([[ -4.,   3.,  -3.],
        [ -4.,  -9.,  -3.],
        [-10.,  -2.,   6.]])
Tổng của toàn bộ Torch Tensor: 
-26.0
Tổng của Torch Tensor theo cột: 
tensor([-18.,  -8.,   0.])
Tổng của Torch Tensor theo hàng: 
tensor([ -4., -16.,  -6.])


In [43]:
tf.tensor3 = tf.constant(arr3)
print('Tensor : \n', tf.tensor3)
print(f'Tổng của toàn bộ Tensor: \n{tf.reduce_sum(tf.tensor3)}')
print(f'Tổng của Tensor theo cột: \n{tf.reduce_sum(tf.tensor3, axis=0)}')
print(f'Tổng của Tensor theo hàng: \n{tf.reduce_sum(tf.tensor3, axis=1)}')

Tensor : 
 tf.Tensor(
[[ -4   3  -3]
 [ -4  -9  -3]
 [-10  -2   6]], shape=(3, 3), dtype=int32)
Tổng của toàn bộ Tensor: 
-26
Tổng của Tensor theo cột: 
[-18  -8   0]
Tổng của Tensor theo hàng: 
[ -4 -16  -6]
