#### Câu 1:
Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor trong khoảng [0, 10) với step=1?

In [1]:
import numpy as np
np.random.seed(2024)
import torch
torch.manual_seed(2024)
import tensorflow as tf
tf.random.set_seed(2024)

In [2]:
arr_arange = np.arange(10)
print(arr_arange)
tensor_arange = torch.arange(10)
print(tensor_arange)
tf_arange = tf.range(10)
print(tf_arange)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


#### Câu 2:
Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor là ma trận đơn vị với kích thước (3, 3).

In [3]:
arr_eye = np.eye(3)
print(arr_eye)
tensor_eye = torch.eye(3)
print(tensor_eye)
tf_eye = tf.eye(3)
print(tf_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


#### Câu 3:
Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor ngẫu nhiên trong khoảng giá trị [0, 1] với kích thước (3, 4). Tiếp theo hãy tạo array, tensor với các giá trị là số nguyên trong khoảng [-10, 10]. Lưu ý trong bài tập này, các bạn sẽ sử dụng seed = 2024 để dảm bảo ra kết quả giống đáp án, cách sử dụng như sau:

In [4]:
arr_random1 = np.random.rand(3,4)
print(arr_random1)
arr_random2 = np.random.randint(-10,10,(3,4))
print(arr_random2)
tensor_random1 = torch.rand(3,4)
print(tensor_random1)
tensor_random2 = torch.randint(-10,10,(3,4))
print(tensor_random2)
tf_random1 = tf.random.uniform((3,4))
print(tf_random1)
tf_random2 = tf.random.uniform((3,4), minval=-10, maxval=10, dtype=tf.dtypes.int32)
print(tf_random2)


[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
[[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]
tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
